package example:host;

world main {
    export run: func(args: list<string>) -> tuple<list<string>, string>;
    export run-many: func(a: s32, b: s32, c: s32, d: s32, e: s32, f: s32, g: s32, h: s32, i: s32, j: s32, k: s32, l: s32, m: s32, n: s32, o: s32, p: s32, q: s32) -> list<s32>
    export run-list: func(args: list<list<s32>>) -> list<list<s32>>;

    export run-variant: func(v: list<my-variant>) -> my-variant;

    variant my-variant {
        a,
        b(string),
        c(string),
    }
    // import get-host-name: func() -> string;
    // import get-value: func(key: u32) -> (a: u64, b: float32);
    // import get-value-tuple: func(key: u32) -> tuple<u64, float32>;
    // import get-value-tuple2: func(key: u32) -> (a: tuple<u64, float32>, b: tuple<string, string>);

    // import print: func(msg: string);

    // export run: func(args: list<string>) -> result<s32, string>;

    // export get-guest-name: func() -> string;
    
}
