package example:host

world main {
    import get-host-name: func() -> string;
    import get-value: func(key: u32) -> (a: u64, b: float32);
    import get-value-tuple: func(key: u32) -> tuple<u64, float32>;
    import get-value-tuple2: func(key: u32) -> (a: tuple<u64, float32>, b: tuple<string, string>);

    import print: func(msg: string);

    export run: func(args: list<string>) -> result<s32, string>;

    export get-guest-name: func() -> string;
    
}
